#!/usr/bin/env python3
"""Generate a demand YAML from a portals inventory.

Class-weighted origin flows: each non-fragment origin lane gets veh/h from
its OSM road class (defaults below, override with --rate class=veh_h).
Minor classes (residential/service/unclassified/track/path) and fragment
stubs are skipped — boundary demand enters on classified roads only.

Usage:
  mkdemand.py --portals portals.json [--rate motorway=1400] ... \
      [--truck 0.08] --out demand/main.yaml

The derivation is napkin math by design (phase 1): rates are per-lane
peak-hour estimates, anchored to published counts in the scenario README
where they exist. Pure stdlib + PyYAML-free emission (YAML subset writer).
"""
import argparse
import json
import sys

DEFAULT_RATES = {  # veh/h per origin lane, AM-peak napkin values
    "motorway": 1400,
    "trunk": 900,
    "primary": 500,
    "secondary": 300,
    "tertiary": 200,
    "motorway_link": 500,
    "trunk_link": 400,
    "primary_link": 300,
    "secondary_link": 200,
    "tertiary_link": 150,
}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--portals", required=True)
    ap.add_argument("--rate", action="append", default=[],
                    help="override class rate, e.g. --rate motorway=1600")
    ap.add_argument("--truck", type=float, default=0.08,
                    help="truck fraction on motorway/trunk classes (arterials get half)")
    ap.add_argument("--total", type=int, default=0,
                    help="scale all rates so injected demand sums to this veh/h "
                         "(flows scaled below --min-rate are dropped)")
    ap.add_argument("--min-rate", type=int, default=60,
                    help="drop scaled flows under this veh/h (with --total)")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    rates = dict(DEFAULT_RATES)
    for r in args.rate:
        cls, _, v = r.partition("=")
        rates[cls] = int(v)

    with open(args.portals) as f:
        portals = json.load(f)

    flows = []
    skipped = {"fragments": 0, "minor": 0, "scaled-out": 0}
    for p in portals["origins"]:
        if p.get("fragment"):
            skipped["fragments"] += 1
            continue
        cls = p.get("class", "")
        vh = rates.get(cls)
        if vh is None:
            skipped["minor"] += 1
            continue
        heavy = cls.startswith(("motorway", "trunk"))
        truck = args.truck if heavy else args.truck / 2
        flows.append((p["id"], cls, vh, round(1 - truck, 3), round(truck, 3)))

    if args.total > 0:
        raw = sum(f[2] for f in flows)
        if raw > 0:
            scale = args.total / raw
            kept = []
            for lane, cls, vh, car, truck in flows:
                v = max(1, round(vh * scale))
                if v < args.min_rate:
                    skipped["scaled-out"] += 1
                    continue
                kept.append((lane, cls, v, car, truck))
            flows = kept

    flows.sort(key=lambda f: -f[2])  # heaviest first, for readability
    total = sum(f[2] for f in flows)
    with open(args.out, "w") as f:
        f.write("# Generated by scripts/chicago/mkdemand.py — class-weighted portal\n")
        f.write("# demand (phase-1 napkin math; see scenario README for anchors).\n")
        f.write(f"# {len(flows)} flows, {total} veh/h total injected. "
                f"Skipped: {skipped['fragments']} fragments, {skipped['minor']} minor-class, "
                f"{skipped['scaled-out']} scaled below the {args.min_rate} veh/h floor.\n")
        f.write("format_version: 1\nflows:\n")
        for i, (lane, cls, vh, car, truck) in enumerate(flows):
            f.write(f"  - id: p{i:03d}-{cls}\n")
            f.write(f"    origin: {lane}\n")
            f.write(f"    veh_per_h: {vh}\n")
            f.write(f"    spacing: poisson\n")
            f.write(f"    vtypes:\n      car: {car}\n      truck: {truck}\n")
    print(f"mkdemand: {len(flows)} flows, {total} veh/h total -> {args.out} "
          f"(skipped {skipped['fragments']} fragments, {skipped['minor']} minor, "
          f"{skipped['scaled-out']} scaled-out)",
          file=sys.stderr)


if __name__ == "__main__":
    main()
