#!/usr/bin/env python3
"""Emit an ADR-0014 §5 metrics part covering every lane of a network.

    mkmetrics.py --network chi-loop-urban.json --out metrics/main.yaml \\
        --begin-s 600 --period-s 300

WHY THIS EXISTS
--------------------------------------------------------------------------
Without a metrics part the kernel measures one interval per lane spanning
the WHOLE run. That makes a warmup impossible to apply after the fact: a
run starting from an empty network spends its first minutes filling, and an
interval that begins at tick 0 has the fill baked into its averages with no
way to subtract it.

`window.begin_s` moves the start of measurement instead, so the numbers
describe loaded conditions only, and `period_s` splits the rest into
intervals so a comparison can look at how the network evolves rather than
at one number per lane.

There is no wildcard in the grammar (`elements` is a checked list of lane
ids), which is deliberate — a set names what it measures — so the list is
generated here rather than hand-written for 55,555 lanes.

Pure stdlib: the output is the flat YAML subset the loader accepts, written
directly so a 55k-element list does not go through a YAML emitter.
"""
import argparse
import json
import sys


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--network", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--begin-s", type=float, default=0.0,
                    help="skip the fill-up transient: start measuring here")
    ap.add_argument("--period-s", type=float, default=300.0)
    ap.add_argument("--end-s", type=float, default=0.0,
                    help="0 = run horizon")
    ap.add_argument("--set-id", default="net")
    ap.add_argument("--metrics", default="edie,time_loss,stops,occupancy")
    ap.add_argument("--no-trips", action="store_true")
    args = ap.parse_args()

    with open(args.network) as f:
        net = json.load(f)
    lane_ids = [L["id"] for L in net["lanes"]]
    if not lane_ids:
        sys.exit("network has no lanes")

    with open(args.out, "w") as f:
        f.write("# Generated by scripts/chicago/mkmetrics.py — whole-network\n")
        f.write("# measurement set (ADR-0014 §5). begin_s skips the fill-up\n")
        f.write("# transient so the numbers describe loaded conditions.\n")
        f.write("format_version: 1\n")
        if not args.no_trips:
            f.write("trips: {}\n")
        f.write("sets:\n")
        f.write(f"  - id: {args.set_id}\n")
        f.write("    metrics:\n")
        for m in args.metrics.split(","):
            f.write(f"      - {m.strip()}\n")
        f.write("    window:\n")
        f.write(f"      period_s: {args.period_s:g}\n")
        if args.begin_s:
            f.write(f"      begin_s: {args.begin_s:g}\n")
        if args.end_s:
            f.write(f"      end_s: {args.end_s:g}\n")
        f.write("    elements:\n")
        for lid in lane_ids:
            f.write(f"      - {lid}\n")

    print(f"[mkmetrics] {len(lane_ids)} lanes, period {args.period_s:g}s, "
          f"begin {args.begin_s:g}s -> {args.out}", file=sys.stderr)


if __name__ == "__main__":
    main()
